def nhahang(gar, ham, coc):
    print('chào mừng các bạn đến với nhà hàng thức ăn nhanh!')
    print('Mời bạn nhập số lượng từng món ăn:')
    print('')
    print('Gà rán:', gar)
    print('Hamburger:', ham)
    print('Cocacola:', coc)
    print('')
    print('Hóa đơn:')
    print('Gà rán               30.000đ x ',gar)
    print('Hamburger            25.000đ x ',ham)
    print('Cocacola             10.000đ x ',coc)
    print('')
    print('Tổng:')
    print(f'Gà rán              {gar*30.000} đ')
    print(f'Hamburger           {ham*25.000} đ')
    print(f'Cocacola            {coc*10.000} đ')
    print(f'Tổng trước thuế     {gar*30.000+ham*25.000+coc*10.000} đ')
    print(f'Thuế(5%)            {(gar*30.000+ham*25.000+coc*10.000)*0.05} đ')
    print(f'Tổng sau thuế       {(gar*30.000+ham*25.000+coc*10.000)+(gar*30.000+ham*25.000+coc*10.000)*0.05} đ')  

if __name__ == '__main__':
    gar = int(input('nhập sl Gà rán  = '))
    ham = int(input('nhập sl Hamburger  = '))
    coc = int(input('nhập sl Cocacola  = '))
    nhahang(gar, ham, coc)